version: "3.8"

services:

      # --- OSRM Routing Backend ---
  osrm:
    image: osrm/osrm-backend
    container_name: gridz-osrm
    command: osrm-routed --algorithm mld /data/north-america-latest.osrm
    ports:
      - "5355:5000"
    volumes:
      - ./osrm-data:/data
    restart: unless-stopped


  # --- Overpass API ---------
  overpass:
    image: wiktorn/overpass-api
    container_name: gridz-overpass
    ports:
      - "12348:80"
    volumes:
      - overpass-db:/db
    environment:
      - OVERPASS_PLANET_URL=https://planet.openstreetmap.org/planet/planet-latest.osm.bz2
    restart: unless-stopped

  # --- PostgreSQL with PostGIS ---
  db:
    image: postgis/postgis:14-3.2
    container_name: gridz-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # --- Redis Queue ---
  redis:
    image: redis:7
    container_name: gridz-redis
    ports:
      - "6381:6379"
    restart: unless-stopped

  # --- Flask Backend API ---
  backend:
    build: ./backend
    container_name: gridz-backend-api
    ports:
      - "5300:5000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: gridz-frontend-ui
    ports:
      - "8010:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: unless-stopped


  # --- NPC Vehicle Simulator ---
  simulator:
    build: ./simulator
    container_name: gridz-vehicle-simulator
    depends_on:
      - backend
      - redis
    restart: unless-stopped

  # --- Auth Service ---
  auth:
    build: ./auth
    container_name: gridz-auth-service
    depends_on:
      - db
    restart: unless-stopped
    
   # --- Real Time Service ---   
  realtime:
    build: ./realtime
    container_name: gridz-realtime
    ports:
      - "6001:6001"
    depends_on:
      - redis
    restart: unless-stopped


volumes:
  pgdata:
  overpass-db:

